# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hero_build.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/hero_build.proto\"A\n\x1b\x43\x43itadelClientMsg_HeroBuild\x12\"\n\nhero_build\x18\x01 \x01(\x0b\x32\x0e.CMsgHeroBuild\"\x89\x07\n\rCMsgHeroBuild\x12\x15\n\rhero_build_id\x18\x01 \x01(\r\x12\x0f\n\x07hero_id\x18\x02 \x01(\r\x12\x19\n\x11\x61uthor_account_id\x18\x03 \x01(\r\x12\x1e\n\x16last_updated_timestamp\x18\x04 \x01(\r\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x10\n\x08language\x18\x07 \x01(\r\x12\x0f\n\x07version\x18\x08 \x01(\r\x12\x17\n\x0forigin_build_id\x18\t \x01(\r\x12*\n\x07\x64\x65tails\x18\n \x01(\x0b\x32\x19.CMsgHeroBuild.Details_V0\x12\x0c\n\x04tags\x18\x0b \x03(\r\x12\x19\n\x11\x64\x65velopment_build\x18\x0c \x01(\x08\x12\x19\n\x11publish_timestamp\x18\r \x01(\r\x1a\x8c\x01\n\rBuildModEntry\x12\x12\n\nability_id\x18\x01 \x01(\r\x12\x12\n\nannotation\x18\x02 \x01(\t\x12\x1b\n\x13required_flex_slots\x18\x03 \x01(\r\x12\x15\n\rsell_priority\x18\x04 \x01(\r\x12\x1f\n\x17imbue_target_ability_id\x18\x05 \x01(\r\x1a\x92\x01\n\x10\x42uildModCategory\x12*\n\x04mods\x18\x01 \x03(\x0b\x32\x1c.CMsgHeroBuild.BuildModEntry\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05width\x18\x04 \x01(\x02\x12\x0e\n\x06height\x18\x05 \x01(\x02\x12\x10\n\x08optional\x18\x06 \x01(\x08\x1a^\n\x0e\x43urrencyChange\x12\x12\n\nability_id\x18\x01 \x01(\r\x12\x15\n\rcurrency_type\x18\x02 \x01(\x05\x12\r\n\x05\x64\x65lta\x18\x03 \x01(\x05\x12\x12\n\nannotation\x18\x04 \x01(\t\x1aG\n\x0c\x41\x62ilityOrder\x12\x37\n\x10\x63urrency_changes\x18\x01 \x03(\x0b\x32\x1d.CMsgHeroBuild.CurrencyChange\x1ay\n\nDetails_V0\x12\x37\n\x0emod_categories\x18\x01 \x03(\x0b\x32\x1f.CMsgHeroBuild.BuildModCategory\x12\x32\n\rability_order\x18\x02 \x01(\x0b\x32\x1b.CMsgHeroBuild.AbilityOrder')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.hero_build_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CCITADELCLIENTMSG_HEROBUILD._serialized_start=26
  _CCITADELCLIENTMSG_HEROBUILD._serialized_end=91
  _CMSGHEROBUILD._serialized_start=94
  _CMSGHEROBUILD._serialized_end=999
  _CMSGHEROBUILD_BUILDMODENTRY._serialized_start=418
  _CMSGHEROBUILD_BUILDMODENTRY._serialized_end=558
  _CMSGHEROBUILD_BUILDMODCATEGORY._serialized_start=561
  _CMSGHEROBUILD_BUILDMODCATEGORY._serialized_end=707
  _CMSGHEROBUILD_CURRENCYCHANGE._serialized_start=709
  _CMSGHEROBUILD_CURRENCYCHANGE._serialized_end=803
  _CMSGHEROBUILD_ABILITYORDER._serialized_start=805
  _CMSGHEROBUILD_ABILITYORDER._serialized_end=876
  _CMSGHEROBUILD_DETAILS_V0._serialized_start=878
  _CMSGHEROBUILD_DETAILS_V0._serialized_end=999
# @@protoc_insertion_point(module_scope)
